apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.apiGateway.name }}
spec:
  replicas: {{ .Values.services.apiGateway.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.apiGateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.apiGateway.name }}
    spec:
      containers:
        - name: {{ .Values.services.apiGateway.name }}
          image: "{{ .Values.images.registry }}/{{ .Values.services.apiGateway.name }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.apiGateway.port }}
          env:
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PRODUCT_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: ORDER_SERVICE_URL
            - name: INVENTORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: INVENTORY_SERVICE_URL
            - name: IDENTITY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: IDENTITY_SERVICE_URL