apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.apiGateway.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.services.apiGateway.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.apiGateway.port }}
      targetPort: {{ .Values.services.apiGateway.port }}
      name: http