apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.identityService.name }}-active
spec:
  selector:
    app: {{ .Values.services.identityService.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.identityService.port }}
      targetPort: {{ .Values.services.identityService.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.identityService.name }}-preview
spec:
  selector:
    app: {{ .Values.services.identityService.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.identityService.port }}
      targetPort: {{ .Values.services.identityService.port }}