apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.notificationService.name }}-active
spec:
  selector:
    app: {{ .Values.services.notificationService.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.notificationService.port }}
      targetPort: {{ .Values.services.notificationService.port }}

--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.notificationService.name }}-preview
spec:
  selector:
    app: {{ .Values.services.notificationService.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.notificationService.port }}
      targetPort: {{ .Values.services.notificationService.port }}