apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.orderService.name }}
spec:
  selector:
    app: {{ .Values.services.orderService.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.orderService.port }}
      targetPort: {{ .Values.services.orderService.port }}