name: Build and Push Docker Images

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: dinhcam89/frontend:latest

      - name: Build and push identity image
        uses: docker/build-push-action@v5
        with:
          context: ./identity
          file: ./identity/Dockerfile
          push: true
          tags: dinhcam89/identity:latest

      - name: Build and push inventory image
        uses: docker/build-push-action@v5
        with:
          context: ./inventory-service
          file: ./inventory-service/Dockerfile
          push: true
          tags: dinhcam89/inventory:latest

      - name: Build and push notification image
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          file: ./notification-service/Dockerfile
          push: true
          tags: dinhcam89/notification:latest

      - name: Build and push order image
        uses: docker/build-push-action@v5
        with:
          context: ./order-service
          file: ./order-service/Dockerfile
          push: true
          tags: dinhcam89/order:latest

      - name: Build and push product image
        uses: docker/build-push-action@v5
        with:
          context: ./product-service
          file: ./product-service/Dockerfile
          push: true
          tags: dinhcam89/product:latest
