name: Build and Push Docker Images

on:
  push:
    branches:
      - prod
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
        IMAGE_TAG: v0.0.7-prod
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push api-gateway image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api-gateway/Dockerfile
          push: true
          tags: dinhcam89/api-gateway:${{ env.IMAGE_TAG }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: dinhcam89/frontend:${{ env.IMAGE_TAG }}

      - name: Build and push identity image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./identity-service/Dockerfile
          push: true
          tags: dinhcam89/identity-service:${{ env.IMAGE_TAG }}

      - name: Build and push inventory image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./inventory-service/Dockerfile
          push: true
          tags: dinhcam89/inventory-service:${{ env.IMAGE_TAG }}

      - name: Build and push notification image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./notification-service/Dockerfile
          push: true
          tags: dinhcam89/notification-service:${{ env.IMAGE_TAG }}

      - name: Build and push order image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./order-service/Dockerfile
          push: true
          tags: dinhcam89/order-service:${{ env.IMAGE_TAG }}

      - name: Build and push product image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./product-service/Dockerfile
          push: true
          tags: dinhcam89/product-service:${{ env.IMAGE_TAG }}
